### PR TITLE
add dockerfile

### LINKED ISSUE #74: Dockerfile?
Hey would be nice to have a dockerfile with all the deps. Whether or not people use docker itself, a dockerfile with versions pegged is pretty good way to ensure repeatable, reliable deployments.

### PR DESCRIPTION
**Pull request by kaakaa**
fixes #74 

I have written dockerfile for oss-dashboard and how to run oss-dashboard docker container.
But my English in README.md may be wrong, so please point it out or fix it.

### CODE REVIEW

**Comment by hyandell** [comment]
Thank you Yusuke :) The English looks pretty good; much better than my Japanese (I'm just starting to try and learn... "my name is" and how to write a i e o u in hiragana :) ).

I'm clueless on docker, so I'll try to follow the readme and see if it works for me. Also other members of the open source team at amazon have been using docker for others of our project, so I'll have them weigh in with more intelligent thoughts ( @jpeddicord  + @jamesiri ).

**Comment by jpeddicord** [comment]
Dockerfile looks great 👍

Long-term it'd be nice to remove postgresql and use [that container directly](https://hub.docker.com/_/postgres/), perhaps via stack/compose file. But this PR should work fine for getting started.

**Comment by kaakaa** [comment]
@hyandell 
Your challenge to start learning Japanese is sounds great to me!
(It may be not `a i e o u` and be `a i u e o` 😃 )
I will be welcoming for your reply in Japanese 😆.

And I found a little mistakes in README.md, so I will be fixing it soon.

@jpeddicord 
Thank you for your reviewing.
I think so too. At first I tried to write docker-compose.yml.
[oss-dashboard/docker-compose.yml at docker · kaakaa/oss-dashboard](https://github.com/kaakaa/oss-dashboard/blob/docker/docker-compose.yml)

But I thought that it has some complexity to add Docker and docker-compose.yml at same time.
So after merged this PR, I'll send next PR about docker-compsoe.

**Comment by hyandell** [comment]
I think we should move to the separate postgresql container, but first I'm going to merge this, fix a couple of typos and mark it as experimental.

Doumo osoreirimasu gozaimashita, Yusuke-san :)

**Comment by hyandell** [comment]
I forgot to ask this - could you confirm that this contribution is under the Apache License, 2.0?

**Comment by kaakaa** [comment]
Dou itashimashite, Henri-san 😃 (meaning `Not at all, Mr. Henri!`)
Thank you for merging!

And yes, I confirm that my patches are under the Apache License 2.0.

**Comment by hyandell** [comment]
Merged :)

**Pull request merged**
